[deployment]
build = "npm run build"
run = "npm start"
deploymentTarget = "autoscale"

[[domains]]
domain = "bookd.tools"

[[domains]]
domain = "www.bookd.tools"

[[domains]]
domain = "app.bookd.tools"

[nix]
channel = "stable-23_11"